# Enable or disable automatic backup
auto:
  enabled: true
  # Interval between automatic backups in ticks (1 second = 20 ticks)
  interval: 72000
  delay: 1

# Whitelist worlds to backup
whitelist_world:
  - world
  - world_nether
  - world_the_end

# Maximum number of backups to store
max_backup:
  enabled: true
  count: 3

# Compression settings
compression:
  # Compression mode: "basic" or "parallel"
  # Note: Parallel mode is experimental and may cause performance issues.
  # It increases the server's memory when using parallel mode.
  mode: basic