whitelist-worlds:
  - world
  - world_nether
  - world_the_end

compression:
  level: 3
print-progress: true

auto-intervention:
  enabled: true
  interval: 3600

max-backup:
  enabled: true
  count: 1