name: HynseBackup
version: '${version}'
main: xyz.hynse.hynsebackup.HynseBackup
api-version: 1.19
author: MidnightTale_
description: easy auto backup for minecraft server.
website: https://hynse.xyz
commands:
  backup:
    description: Manage backups
    usage: /backup <reload|start>
    permission: hynsebackup.use
    aliases: [hb]

permissions:
  hynsebackup.use:
    description: Allows access to all HynseBackup commands
    default: op
  hynsebackup.reload:
    description: Allows reloading the HynseBackup configuration
    default: op
  hynsebackup.start:
    description: Allows starting a backup for a specific world
    default: op

folia-supported: true
load: POSTWORLD
